Bampfa 578: Storage locations finished
cspace-deployment/cspace-ui-plugin-profile-cinefiles.js pull request #1
Opened 2018-03-11 01:48 UTC by cesarvh

2018-03-12 22:32 UTC, ray-lee requested changes
I think there are some customizations here that aren't needed. Please see the comments.

2018-03-12 22:32 UTC, ray-lee commented on src/index.js
> +        },
Don't need to disable local. The local vocab in the UI corresponds to the "location-location" vocab in the app layer (you can tell because the servicePath is 'urn:cspace:name(location)'). So we just need to disable offsite, and change the name of local in messages.js.

2018-03-12 22:32 UTC, ray-lee commented on src/plugins/recordTypes/location/fields.js
> +};
I don't think we need this. In the 4.1 config, we didn't modify the termSource field. Disabling the citation/worldcat vocabulary should be enough to keep it from being bound to this field. Let me know if it's not-- there might be a bug.

2018-03-12 22:32 UTC, ray-lee commented on src/messages.js
> +  'field.collectionobjects_common.referenceNote.name': 'Note',
Not location related, so please remove from this pull request.

2018-03-12 22:32 UTC, ray-lee commented on src/plugins/recordTypes/location/vocabularies.js
> +};
Don't need to add a vocabulary. Just change the name of the local vocabulary in messages.js.

2018-03-12 23:54 UTC, cesarvh commented on src/plugins/recordTypes/location/fields.js
> +};
Tried this out and it works. Removed in the next commit.

2018-03-12 23:57 UTC, cesarvh commented
Committed changes.

2018-03-13 20:13 UTC, ray-lee approved these changes

2018-03-13 20:13 UTC, merged