BAMPFA-583: Collection objects record customizations
cspace-deployment/cspace-ui-plugin-profile-cinefiles.js pull request #12
Opened 2018-04-09 21:33 UTC by cesarvh

2018-04-11 22:45 UTC, ray-lee requested changes
Hi Cesar,
Please see comments. Also there a couple of missing customizations:

- Hide photograph and inventory templates
- Customize search result columns - replace second column with docDisplayName, sorted by docTitle

Thanks.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/idGenerators.js
> +        defaultMessage: 'CineFiles document number',
The word "number" seems redundant. Let's change this to just "CineFiles document".

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/idGenerators.js
> +        defaultMessage: 'PFA stills number',
Let's change to "PFA still".

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +              defaultValue: 'urn:cspace:cinefiles.cspace.berkeley.edu:vocabularies:name(department):item:name(pfalibrary)\'PFA Library\'',
Needs to be changed to a dynamic term list (TermPickerInput).

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +            defaultValue: 'urn:cspace:cinefiles.cspace.berkeley.edu:vocabularies:name(collection):item:name(cinefiles)\'CineFiles\'',
Needs to be changed to a dynamic term list (TermPickerInput).

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/optionLists.js
> +  departments: {
Don't need this. responsibleDepartment was changed to a dynamic term list.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/optionLists.js
> +  collections: {
Don't need this. collection was changed to a dynamic term list.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/optionLists.js
> +export default {
Customization to recordStatuses list is missing.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +        hasCastCrSearch: {},
We no longer need to define separate fields for searching, so all of the checkbox search fields can be removed.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +                defaultMessage: 'Box Office.',
Lowercase office, remove dot.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +                defaultMessage: 'Cost information',
Let's shorten to "Cost info" (no dot) -- looks better at smaller window sizes.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +                defaultMessage: 'With illustration',
Shorten to "With illus." -- looks better at smaller window sizes.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +                  source: 'person/local, organization/local, organization/committee',
Remove spaces. Organization vocabs aren't appearing in the Add to menu.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +                defaultMessage: 'Display Name',
Lowercase n.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +                  source: 'concept/associated, concept/genre',
Remove space.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +                  source: 'organization/local, organization/committee',
Remove space.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +                  source: 'person/local',
Disabling the other person vocabularies is enough to prevent them from being tied to the field, so this can be removed. The repeating and type properties weren't changed from the default, so the whole contentPersons block can go.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +              repeating: true,
repeating not changed from the default, so it can be removed here.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +                type: AutocompleteInput,
type not changed from default, so remove this.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +                defaultMessage: 'External document URL details',
This label was in 4.1, but I don't think it adds anything to the section header right above it. Let's remove this message.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +            },
It would be good to also change the referenceNote field (now relabeled "URL") to be a URLInput instead of TextInput, so that the URL will be linked.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +              },
type wasn't changed from the default, and disabling the other place vocabs is enough to remove them from the field, so the whole fieldCollectionPlace block can be removed.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/forms/default.jsx
> +
objectStatusList and colors are losing their left/right margin (a bug). For now, wrap each in a <Col>, that should fix it.

2018-04-11 22:45 UTC, ray-lee commented on src/messages.js
> +  'panel.collectionobject.reference': 'External document URL information',
Panel headers should be title case.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/fields.js
> +            }),
Need to configure a searchView, or else the field will also be read only on the search form.

2018-04-11 22:45 UTC, ray-lee commented on src/plugins/recordTypes/collectionobject/advancedSearch.js
> +        path: 'ns2:collectionobjects_cinefiles/pageInfo',
should be ns2:collectionobjects_common/numberOfObjects.

2018-04-17 09:45 UTC, cesarvh commented
Hi Ray,

I've gone ahead and pushed the requested changes.

2018-05-01 05:57 UTC, merged