BAMPFA-582/BAMPFA-591: Works authority and advanced search customizations
cspace-deployment/cspace-ui-plugin-profile-cinefiles.js pull request #9
Opened 2018-03-28 02:56 UTC by cesarvh

In the diff both, BAMPFA-580/90 and BAMPFA-582/591 are shown. Let me know if you need me to make

2018-04-01 23:29 UTC, cesarvh commented
Hi Ray,

I rebased the branch like you, and it the extra diffs went away. Should be good now.

2018-04-02 23:23 UTC, ray-lee requested changes
Hi Cesar,
A few changes to make, please. Also need to configure search result columns (show creator instead of term status). I think bampfa has some examples of this (columns.js). In the 4.1 config, if you see changes to "mini", it means that search result columns have been modified.

Thanks!

2018-04-02 23:23 UTC, ray-lee commented on src/plugins/optionLists/shared.js
> +      messages: defineMessages({
These values won't ever be translated, since they're already in the language that they need to be in, and the values are all identical to the labels. So we can remove messages for this list.

2018-04-02 23:23 UTC, ray-lee commented on src/plugins/optionLists/shared.js
> +        'El',
Should be `El-`

2018-04-02 23:23 UTC, ray-lee commented on src/plugins/optionLists/shared.js
> +        'L',
Should be `L'`

2018-04-02 23:23 UTC, ray-lee commented on src/plugins/optionLists/shared.js
> +        'Un',
Should be `Un'`

2018-04-02 23:23 UTC, ray-lee commented on src/plugins/optionLists/shared.js
> +      ],
Please double check all values. These need to be identical to the values in 4.1. I caught a few differences above.

2018-04-02 23:23 UTC, ray-lee commented on src/plugins/recordTypes/work/fields.js
> +                type: OptionPickerInput,
Should be type `TermPickerInput`, source `languages`.

2018-04-02 23:23 UTC, ray-lee commented on src/plugins/recordTypes/work/forms/default.jsx
> +            <Field name="genres" subpath="ns2:works_cinefiles">
Move genre above work date to match 4.1 layout.

2018-04-02 23:23 UTC, ray-lee commented on src/plugins/recordTypes/work/forms/default.jsx
> +        <Field name="addrGroupList">
Let's remove the address group. This was added to core, but I'm pretty sure cinefiles won't use it.

2018-04-02 23:23 UTC, ray-lee commented on src/plugins/recordTypes/work/advancedSearch.js
> +      },
Let's move termName above termDisplayName. We probably should have done that before, since we repositioned them on the record editor.

2018-04-02 23:23 UTC, ray-lee commented on src/plugins/recordTypes/utils.js
> +  const article = data.get('termQualifier' || '');
Should be` data.get('termQualifier') || ''`

2018-04-02 23:23 UTC, ray-lee commented on src/plugins/recordTypes/utils.js
> +  const title = data.get('termName' || '');
Should be `data.get('termName') || ''`

2018-04-04 00:51 UTC, cesarvh commented
Hi Ray,

I went through and made the changes. I'm not entirely sure if columns.js is as it should be, but I just followed what was on cspace-ui.js and cspace-deployment/cspace-ui-plugin-profile-bampfa.js. Particularly, I'm not sure if `sortBy: 'works_common:workTermGroupList/0/creator'` is correct or not. 

Thanks!

2018-04-04 19:02 UTC, cesarvh commented
Hi Ray,

I believe the requested changes are done.

2018-04-05 08:12 UTC, ray-lee requested changes
A couple changes needed.

2018-04-05 08:12 UTC, ray-lee commented on src/plugins/recordTypes/work/fields.js
> +                  source: 'language',
Does this term list load? I think it should be 'languages'.

2018-04-05 08:12 UTC, ray-lee commented on src/plugins/recordTypes/work/columns.js
> +        sortBy: 'works_common:workTermGroupList/0/creator',
Look at the path to the field in fields.js to see what this should be. So `works_common:creatorGroupList/0/creator`.  Test if you have it configured correctly by doing a search, and seeing if clicking on the column header results in the rows being sorted as expected.

2018-04-09 22:47 UTC, ray-lee commented
Customization of mini form is incomplete. I'll make a separate issue for that -- I'll need to fix a bug in cspace-ui so that we can show just the second term display name and first creator. (Also work date needs to be added).

2018-04-09 22:47 UTC, merged